### ISSUE TITLE
Implement "tojson" filter

### ISSUE THREAD

**Issue by rakeshkky** [tdammers/ginger#11]
Need tojson filter in which `{{ info | tojson }}` should interpolate JSON value of  `info` while rendering.

For example, my data type is
`data Interpolate = Interpolate { info :: Data.Aeson.Object }` which is `ToJSON` instance.

**Comment by tdammers** [comment]
This should do the trick (documentation [here](http://ginger.tobiasdammers.nl/guide/syntax/filters#jsonx-prettytrue)). You still need to provide a `ToGVal` instance for your type, but that shouldn't be too hard to figure out.
