### ISSUE TITLE
`keepTrailingNewline` option not passed on to includes

### ISSUE THREAD

**Issue by tdammers** [tdammers/ginger#9]
With 'poKeepTrailingNewline = True' the main template keeps the newline but the included templates still swallow it. Here is a sample...
my template:
line1: {{v1}}\nline2: {% include 'line2inc' %}\nline3: {{v2}}!\nline4: {% for i in [1,2,3] %}{{i}}{% endfor %}\nline5
with this include:
{% for i in [1,2,3] %}{{i}}{% endfor %}\n(2nd inc line)

produces this:
line1: v1
line2: 123(2nd inc line)
line3: v2!
line4: 123
line5

but it should keep the newline in front of '(2nd inc line)'

(Split off from #8)

**Comment by agreif** [comment]
here a more comprehensive test with nested includes:

template:

    line1: {{v1}}\nline2: {% include 'line2inc' %}\nline7: {{v2}}!\nline8: {% for i in [1,2,3] %}{{i}}{% endfo\r %}\nline9

includes:

      "./line2inc" -> "{% for i in [1,2,3] %}{{i}}{% endfor %}\nline3\n{% include 'line4inc' %}\nline6"
      "./line4inc" -> "line4: {% for i in [1,2,3] %}{{i}}{% endfor %}\nline5"
 
produces:

    line1: v1
    line2: 123line3
    line4: 123line5line6
    line7: v2!
    line8: 123
    line9

inside the includes the \n is swallowed after the %}

**Comment by agreif** [comment]
thanks for the quick fix!
now the following is the correct result:

    line1: v1
    line2: 123
    line3
    line4: 123
    line5
    line6
    line7: v2!
    line8: 123
    line9
